export type LabSafety = "Child can try" | "Grown-up nearby" | "Grown-up required";

export type ScienceLab = {
  id: string;
  title: string;
  icon: string;
  field: string;
  safety: LabSafety;
  time: string;
  question: string;
  materials: string[];
  steps: string[];
  predictions: [string, string, string];
  observation: string;
  explanation: string;
  wonder: string;
};

const labs: ScienceLab[][] = [
  [
    { id: "shadow-hunt", title: "Shadow Hunt", icon: "👤", field: "Light", safety: "Child can try", time: "5 min", question: "What happens to a shadow when an object moves?", materials: ["a sunny window or lamp", "one toy"], steps: ["Put the toy where light reaches it.", "Find its shadow.", "Move the toy closer to and farther from the light."], predictions: ["The shadow changes", "The toy changes color", "Nothing changes"], observation: "Point to where the shadow became bigger, smaller, or moved.", explanation: "Light travels until an object blocks it. The dark area behind the object is its shadow.", wonder: "Can you make two shadows from one toy?" },
    { id: "roll-or-stay", title: "Roll or Stay?", icon: "⚽", field: "Motion", safety: "Child can try", time: "5 min", question: "Which shapes roll easily?", materials: ["a ball", "a block", "a safe flat floor"], steps: ["Gently push the ball.", "Gently push the block.", "Compare how they move."], predictions: ["The ball rolls farther", "The block rolls farther", "They move the same"], observation: "Notice which object turns over and over.", explanation: "Round surfaces can keep turning. Flat faces often stop an object from rolling.", wonder: "What happens on a small ramp?" },
    { id: "ice-watch", title: "Ice Watch", icon: "🧊", field: "Matter", safety: "Grown-up nearby", time: "10 min", question: "What happens when ice gets warm?", materials: ["one ice cube", "a bowl", "a towel"], steps: ["Put the ice in the bowl.", "Look and touch gently.", "Wait and look again."], predictions: ["It becomes liquid water", "It grows", "It becomes a rock"], observation: "Look for drops and a change in shape.", explanation: "Warmth gives the ice energy. Solid water melts into liquid water.", wonder: "Would ice melt faster in sun or shade?" },
    { id: "color-meeting", title: "Colors Meet", icon: "🎨", field: "Color", safety: "Grown-up nearby", time: "8 min", question: "What new colors can two colors make?", materials: ["washable red, yellow, and blue paint", "paper", "brush"], steps: ["Put down two tiny paint dots.", "Mix them in the middle.", "Try a different pair."], predictions: ["A new color appears", "All color disappears", "The paper becomes clear"], observation: "Name each color before and after mixing.", explanation: "Paints absorb and reflect different parts of light. Mixing changes the light that reaches our eyes.", wonder: "How many greens can you make?" },
    { id: "sound-search", title: "Sound Search", icon: "👂", field: "Sound", safety: "Child can try", time: "5 min", question: "Can we hear a vibration?", materials: ["your hands", "your voice", "a quiet room"], steps: ["Hum gently.", "Touch two fingers to your throat.", "Stop humming and compare."], predictions: ["I feel a buzz while humming", "My hand changes color", "Nothing can be felt"], observation: "Describe the tiny movement you feel.", explanation: "Sound begins with vibration—a quick back-and-forth movement that travels through matter.", wonder: "Do high and low hums feel the same?" },
    { id: "float-look", title: "Float Look", icon: "🛶", field: "Buoyancy", safety: "Grown-up nearby", time: "8 min", question: "Do all objects sink in water?", materials: ["a shallow bowl of water", "a leaf", "a spoon", "a cork or bottle cap", "a towel"], steps: ["Predict for each object.", "Place one object in the bowl.", "Sort it as floating or sinking."], predictions: ["Some float and some sink", "Everything floats", "Everything sinks"], observation: "Compare material, shape, and whether air is trapped.", explanation: "Water pushes upward. An object floats when that upward push can balance its weight.", wonder: "Can clay float if its shape changes?" },
    { id: "texture-detective", title: "Texture Detective", icon: "🖐️", field: "Observation", safety: "Child can try", time: "5 min", question: "How can touch help us compare things?", materials: ["a soft cloth", "a smooth spoon", "a bumpy safe toy"], steps: ["Touch each object.", "Choose words for how it feels.", "Sort smooth, soft, or bumpy."], predictions: ["They feel different", "They all feel the same", "Touch changes their size"], observation: "Use describing words instead of only naming the object.", explanation: "Skin contains receptors that respond to pressure, temperature, and texture.", wonder: "Can two objects feel alike but look different?" },
    { id: "plant-drink", title: "Does a Plant Drink?", icon: "🌱", field: "Life science", safety: "Grown-up nearby", time: "10 min + wait", question: "Where does water enter a plant?", materials: ["a small plant", "water", "an adult-approved cup"], steps: ["Feel whether the soil is dry.", "Add a small amount of water.", "Look again later."], predictions: ["Water moves into the soil", "Water jumps upward", "The plant disappears"], observation: "Notice soil color and how the plant looks later.", explanation: "Roots absorb water from soil. Water then moves through tiny tubes inside the plant.", wonder: "What changes after several days of careful watering?" },
  ],
  [
    { id: "paper-bridge", title: "Paper Bridge", icon: "🌉", field: "Engineering", safety: "Child can try", time: "15 min", question: "Can folding make paper stronger?", materials: ["two cups", "two sheets of paper", "coins or blocks"], steps: ["Lay flat paper across the cups.", "Add weights one at a time.", "Fold the other paper like an accordion and test again."], predictions: ["Folded paper holds more", "Flat paper holds more", "Folding makes no difference"], observation: "Count how many equal weights each bridge holds.", explanation: "Folds change the paper's shape and spread forces through more stiff edges.", wonder: "Which fold pattern makes the strongest bridge?" },
    { id: "magnet-map", title: "Magnet Map", icon: "🧲", field: "Magnetism", safety: "Grown-up nearby", time: "10 min", question: "Which materials respond to a magnet?", materials: ["a child-safe magnet", "paper clip", "wooden pencil", "plastic lid", "spoon"], steps: ["Predict each object.", "Bring the magnet close without throwing it.", "Record yes or no."], predictions: ["Only some metals respond", "Everything responds", "Only plastic responds"], observation: "Notice that 'metal' is not a complete rule—many, but not all, metals are magnetic.", explanation: "Magnets strongly attract materials such as iron and steel because of how magnetic regions inside them line up.", wonder: "Can the magnet pull through paper?" },
    { id: "seed-window", title: "Seed Window", icon: "🌱", field: "Plant science", safety: "Grown-up nearby", time: "10 min + days", question: "Which part appears first when a seed sprouts?", materials: ["bean seed", "damp paper towel", "clear reusable container"], steps: ["Place the damp towel and seed in the container.", "Leave it open enough for air and place safely near light.", "Draw what changes each day."], predictions: ["A root appears first", "A flower appears first", "A fruit appears first"], observation: "Look for a tiny root, then a shoot and leaves.", explanation: "The first root anchors the plant and begins taking in water. The shoot then grows toward light.", wonder: "Does warmth change sprouting speed?" },
    { id: "walking-water", title: "Walking Water", icon: "💧", field: "Capillary action", safety: "Grown-up nearby", time: "15 min + wait", question: "Can water move upward through paper?", materials: ["two cups", "water", "paper towel", "washable food color optional"], steps: ["Put water in one cup.", "Bridge the cups with a folded paper towel touching both bottoms.", "Watch over time."], predictions: ["Water climbs and crosses", "Water stays only below", "Paper pushes water away"], observation: "Mark the water level and watch the wet area travel.", explanation: "Water sticks to paper fibers and to itself, letting it move through tiny spaces against gravity.", wonder: "Does a wider paper strip change the speed?" },
    { id: "dissolve-race", title: "Dissolve Race", icon: "🥄", field: "Mixtures", safety: "Grown-up nearby", time: "10 min", question: "Does stirring change how fast a solid dissolves?", materials: ["two clear cups of equal water", "two equal spoons of sugar", "spoon"], steps: ["Add equal sugar to both cups.", "Stir only one cup the same number of times.", "Compare what remains. Do not taste."], predictions: ["Stirred sugar dissolves faster", "Unstirred dissolves faster", "Stirring has no effect"], observation: "Look for grains remaining at the bottom.", explanation: "Stirring moves fresh water past the sugar surface, carrying dissolved particles away faster.", wonder: "How could you test water temperature fairly with an adult?" },
    { id: "rain-gauge", title: "Build a Rain Gauge", icon: "🌧️", field: "Weather", safety: "Grown-up required", time: "15 min + rain", question: "How can we measure rainfall?", materials: ["adult-cut straight-sided clear container", "ruler", "marker"], steps: ["Ask an adult to prepare the container.", "Mark equal distances from the bottom.", "Place it securely outside and read after rain."], predictions: ["Water level measures rainfall", "Container color measures rainfall", "Wind alone fills it"], observation: "Read at eye level and use the same units each time.", explanation: "Rainfall depth tells how high collected rain would cover a flat surface if it did not run away.", wonder: "Does every part of your yard collect the same amount?" },
    { id: "ramp-test", title: "Ramp Test", icon: "🛝", field: "Forces and motion", safety: "Child can try", time: "10 min", question: "How does ramp height affect rolling distance?", materials: ["cardboard ramp", "ball", "books", "measuring blocks"], steps: ["Roll from a low ramp without pushing.", "Measure distance with blocks.", "Raise the ramp and repeat from the same start."], predictions: ["Higher ramp rolls farther", "Lower ramp rolls farther", "Height never matters"], observation: "Change only ramp height to keep the comparison fair.", explanation: "A higher start stores more gravitational potential energy, which changes into motion.", wonder: "What happens with a rough surface?" },
    { id: "shadow-clock", title: "Shadow Clock", icon: "☀️", field: "Earth and space", safety: "Grown-up nearby", time: "10 min + revisit", question: "Why does a shadow move during the day?", materials: ["chalk", "a standing object outside", "grown-up supervision"], steps: ["Mark the shadow tip.", "Write the time.", "Return later and mark again."], predictions: ["The shadow moves as Earth turns", "The object walks", "The Sun circles the yard"], observation: "Compare direction and length at each time.", explanation: "Earth rotates, changing the Sun's apparent position and the direction of shadows.", wonder: "When is the shadow shortest?" },
  ],
  [
    { id: "pendulum-pattern", title: "Pendulum Pattern", icon: "⏱️", field: "Motion", safety: "Grown-up nearby", time: "15 min", question: "What changes a pendulum's swing time most?", materials: ["string", "washer", "tape", "timer"], steps: ["Have an adult secure the pendulum.", "Time ten small swings.", "Change string length and repeat. Keep release angle small."], predictions: ["String length matters", "Washer color matters", "Day of week matters"], observation: "Divide total time by ten for one swing.", explanation: "For small swings, a longer pendulum has a longer period. Mass has little effect on the period.", wonder: "What graph could show length versus period?" },
    { id: "erosion-tray", title: "Erosion Engineer", icon: "🏞️", field: "Earth science", safety: "Grown-up nearby", time: "20 min", question: "How does flowing water shape land?", materials: ["shallow tray", "soil or sand", "small cup of water", "towel"], steps: ["Build a gentle hill in the tray.", "Pour the same small stream from one end.", "Sketch channels and deposited sediment."], predictions: ["Water moves sediment downhill", "Water builds an upward river", "Soil never moves"], observation: "Find both erosion and deposition.", explanation: "Moving water removes sediment where energy is higher and deposits it as the flow slows.", wonder: "Can plants or pebbles reduce erosion?" },
    { id: "insulation-race", title: "Keep the Ice", icon: "🧊", field: "Heat transfer", safety: "Grown-up nearby", time: "20 min", question: "Which material slows melting best?", materials: ["equal ice cubes", "small cloth", "paper", "foil", "plates"], steps: ["Wrap equal ice cubes in different materials.", "Leave one unwrapped as a control.", "Compare after the same time."], predictions: ["Some wraps slow heat transfer", "Wrapping creates cold", "All must melt equally"], observation: "Measure remaining size or meltwater consistently.", explanation: "Insulators slow energy transfer from warmer surroundings to colder ice.", wonder: "How would multiple layers change the result?" },
    { id: "surface-tension", title: "Pepper Escape", icon: "💧", field: "Surface tension", safety: "Grown-up nearby", time: "10 min", question: "How can soap change water's surface?", materials: ["shallow dish of water", "pepper", "dish soap", "cotton swab"], steps: ["Sprinkle a little pepper on water.", "Touch the center with a clean swab.", "Try again with a tiny soap-coated swab. Do not taste."], predictions: ["Pepper moves away from soap", "Pepper turns to ice", "Soap makes light"], observation: "Compare clean and soapy swabs.", explanation: "Soap lowers surface tension. Water pulls more strongly away from the soapy spot, carrying pepper outward.", wonder: "Does the amount of soap change the motion?" },
    { id: "chromatography", title: "Ink Color Detective", icon: "🖊️", field: "Mixtures", safety: "Grown-up nearby", time: "20 min", question: "Can one ink contain several pigments?", materials: ["washable markers", "coffee-filter strips", "water", "cup"], steps: ["Draw a marker dot above the strip's bottom.", "Stand only the strip bottom in water; keep the dot above water.", "Watch colors travel. Do not drink."], predictions: ["Some inks separate into colors", "Paper becomes metal", "Ink moves downward only"], observation: "Record the colors and how far each travels.", explanation: "Water carries soluble pigments. Different pigments move at different rates because of solubility and attraction to paper.", wonder: "Do two black markers make the same pattern?" },
    { id: "lever-lift", title: "Lever Lift", icon: "🏗️", field: "Simple machines", safety: "Grown-up nearby", time: "12 min", question: "How does fulcrum position change effort?", materials: ["ruler", "pencil as fulcrum", "small safe object"], steps: ["Balance the ruler on the pencil.", "Place the object on one end.", "Move the fulcrum and compare the push needed."], predictions: ["Fulcrum position changes effort", "Ruler color changes effort", "Nothing can change effort"], observation: "Notice effort distance and load distance.", explanation: "A lever trades force for distance. A longer effort arm can lift a load with less force.", wonder: "Where are levers hiding in playgrounds?" },
    { id: "water-cycle-model", title: "Water Cycle Window", icon: "☁️", field: "Earth systems", safety: "Grown-up required", time: "15 min + wait", question: "Can water change state and move in a closed model?", materials: ["resealable clear bag", "small amount of water", "tape", "sunny window"], steps: ["An adult adds water and seals the bag.", "Tape it securely to a window.", "Observe droplets over several hours without opening or tasting."], predictions: ["Water evaporates and condenses", "Water vanishes forever", "The bag makes new matter"], observation: "Find liquid below, vapor you cannot see, and droplets above.", explanation: "Energy drives evaporation; cooling causes condensation. Matter moves through the system rather than disappearing.", wonder: "How is this model unlike Earth's full water cycle?" },
    { id: "balloon-rocket", title: "Balloon Rocket", icon: "🚀", field: "Newton's laws", safety: "Grown-up required", time: "15 min", question: "How can escaping air push a balloon forward?", materials: ["balloon", "straw", "string", "tape"], steps: ["An adult threads string through the straw and secures it tightly.", "Tape an inflated, unknotted balloon to the straw.", "Release away from faces; discard broken balloon pieces immediately."], predictions: ["Air backward pushes balloon forward", "Gravity turns off", "String creates fuel"], observation: "Compare direction of air and balloon motion.", explanation: "The balloon pushes air backward; the air pushes the balloon forward with an equal and opposite force.", wonder: "How does balloon size affect distance?" },
  ],
  [
    { id: "density-stack", title: "Density Stack", icon: "🥛", field: "Matter", safety: "Grown-up required", time: "20 min", question: "Why can liquids form layers?", materials: ["clear container", "corn syrup", "water", "vegetable oil", "adult supervision"], steps: ["An adult adds equal small amounts slowly.", "Wait for layers to settle.", "Record the layer order. Do not taste."], predictions: ["Denser liquids settle lower", "Colors decide density", "All liquids must mix"], observation: "Compare mass per equal volume conceptually.", explanation: "Density is mass divided by volume. Less-dense immiscible liquids float above denser ones.", wonder: "How could temperature affect density?" },
    { id: "reaction-evidence", title: "Reaction Evidence", icon: "🧪", field: "Chemistry", safety: "Grown-up required", time: "15 min", question: "What evidence suggests new substances formed?", materials: ["open bowl", "baking soda", "vinegar", "spoon", "towel"], steps: ["Keep the bowl open—never seal this reaction.", "An adult adds a small amount of vinegar to baking soda.", "Observe temperature, bubbles, and remaining materials. Do not taste."], predictions: ["Gas bubbles form", "The mixture freezes solid", "No evidence appears"], observation: "Evidence may include gas, temperature change, light, color, or a new solid.", explanation: "An acid-base reaction rearranges atoms and releases carbon dioxide gas. The atoms are conserved even though substances change.", wonder: "How could you measure gas without sealing the container?" },
    { id: "electromagnet", title: "Electromagnet", icon: "🧲", field: "Electricity", safety: "Grown-up required", time: "15 min", question: "Can electric current create a magnetic field?", materials: ["insulated wire", "iron nail", "fresh 1.5 V battery", "paper clips"], steps: ["An adult wraps insulated wire around the nail.", "Touch wire ends to one small battery for only a few seconds—never use wall electricity.", "Test paper clips, then disconnect immediately if anything warms."], predictions: ["Current makes a temporary magnet", "The nail becomes ice", "Paper clips lose mass"], observation: "Compare the nail with current on and off.", explanation: "Moving electric charges create a magnetic field. Coiled wire concentrates that field around the iron core.", wonder: "How does coil count affect strength?" },
    { id: "solar-oven", title: "Solar Heat Collector", icon: "☀️", field: "Energy transfer", safety: "Grown-up required", time: "30 min", question: "How can surfaces collect solar energy?", materials: ["two covered cups", "white and black paper", "water", "thermometer"], steps: ["An adult wraps one cup black and one white.", "Set equal water amounts in sunlight.", "Measure temperatures without tasting; stop if containers become hot."], predictions: ["Black surface warms more", "White surface always warms more", "Sunlight has no energy"], observation: "Record starting and ending temperature for a fair comparison.", explanation: "Dark surfaces absorb more incoming light and transform more of it into thermal energy.", wonder: "How would insulation change the outcome?" },
    { id: "rate-reaction", title: "Temperature and Dissolving", icon: "🌡️", field: "Particle motion", safety: "Grown-up required", time: "15 min", question: "How does water temperature affect dissolving rate?", materials: ["equal clear cups", "cool and warm—not hot—water", "equal sugar cubes", "timer"], steps: ["An adult prepares equal volumes at safe temperatures.", "Add equal sugar cubes at the same time.", "Do not stir; time and compare. Do not taste."], predictions: ["Warm water dissolves faster", "Cool water always dissolves faster", "Temperature cannot matter"], observation: "Keep volume and sugar size controlled.", explanation: "Warmer particles move faster and collide with the solid more often, generally increasing dissolving rate.", wonder: "How would stirring interact with temperature?" },
    { id: "crater-model", title: "Crater Model", icon: "🌕", field: "Planetary science", safety: "Grown-up nearby", time: "20 min", question: "How do impact speed and size affect craters?", materials: ["tray", "flour", "thin cocoa layer", "small balls", "ruler"], steps: ["Smooth the layers in the tray.", "Drop a ball from a measured low height.", "Measure crater width; repeat with one variable changed."], predictions: ["More impact energy makes a larger crater", "Ball color controls crater size", "Impacts leave no pattern"], observation: "Change only height or ball size per comparison.", explanation: "Impact kinetic energy moves and ejects surface material, making a crater. Greater energy usually produces a larger crater.", wonder: "Why do old craters remain visible on the Moon?" },
    { id: "wave-model", title: "Wave Model", icon: "〰️", field: "Waves", safety: "Grown-up nearby", time: "12 min", question: "Does matter travel with a wave?", materials: ["long rope or spring toy", "floor space", "adult partner"], steps: ["Hold opposite ends safely near the floor.", "Send one gentle pulse.", "Watch a marked point as the pulse passes."], predictions: ["Energy travels while the point returns", "The rope travels across the room", "Matter disappears"], observation: "Separate the wave's direction from the material's motion.", explanation: "A wave transfers energy through a disturbance. The medium's particles oscillate around positions instead of traveling with the wave.", wonder: "How do amplitude and frequency differ?" },
    { id: "dissolving-mass", title: "Mass Before and After Dissolving", icon: "⚖️", field: "Conservation of matter", safety: "Grown-up nearby", time: "15 min", question: "Is matter lost when salt seems to disappear in water?", materials: ["clear cup with lid", "water", "small measured amount of salt", "digital scale", "spoon"], steps: ["Measure the cup, lid, water, and salt together before mixing.", "Add the salt, stir, and replace the lid without heating or shaking.", "Measure the same complete set again. Do not taste."], predictions: ["Total mass stays nearly same", "Salt loses all mass", "Water doubles its mass"], observation: "Measurement uncertainty or spilled drops can cause a small difference, so keep every material in the set.", explanation: "Dissolving spreads salt particles through the water; it does not destroy them. In the complete system, matter and total mass are conserved.", wonder: "How could evaporation change an open-cup measurement over time?" },
  ],
];

export function getScienceLabs(ageWorld: number) {
  return labs[Math.max(0, Math.min(3, Math.floor(ageWorld)))] || labs[0];
}

export function getScienceLab(ageWorld: number, page: number) {
  const group = getScienceLabs(ageWorld);
  return group[(Math.max(1, page) - 1) % group.length];
}

export const LAB_COUNTS = { perAge: labs.map((group) => group.length), total: labs.flat().length };
