export type Subject = "math" | "science";

export type LearningLesson = {
  id: string;
  title: string;
  icon: string;
  bigIdea: string;
  explanation: string;
  example: string;
  question: string;
  choices: [string, string, string];
  answer: string;
  why: string;
  activity: string;
  words: Array<[string, string]>;
};

const mathLessons: LearningLesson[][] = [
  [
    {
      id: "one-and-many",
      title: "One and many",
      icon: "🍎",
      bigIdea: "One means a single thing. Many means more than one.",
      explanation: "Look slowly. Point to each thing as you count it. Pointing helps your eyes and your number words stay together.",
      example: "🍎 is one apple. 🍎🍎🍎 is many apples.",
      question: "Which group has one star?",
      choices: ["⭐", "⭐⭐", "⭐⭐⭐"],
      answer: "⭐",
      why: "There is only one star in that group.",
      activity: "Hold up one finger. Now wiggle many fingers.",
      words: [["one", "a single thing"], ["many", "more than one"]],
    },
    {
      id: "count-to-three",
      title: "Count to three",
      icon: "🐥",
      bigIdea: "The last number you say tells how many there are.",
      explanation: "Touch each chick once: one, two, three. Do not skip one and do not count one twice.",
      example: "🐥 🐥 🐥 → one, two, three chicks.",
      question: "How many balls do you see? ⚽ ⚽",
      choices: ["1", "2", "3"],
      answer: "2",
      why: "Touch them: one, two. There are two balls.",
      activity: "Find three safe things nearby and line them up.",
      words: [["count", "say a number for each thing"], ["three", "one more than two"]],
    },
    {
      id: "same-and-different",
      title: "Same and different",
      icon: "🧦",
      bigIdea: "Things can match in some ways and differ in other ways.",
      explanation: "Look at color, shape and size. Two things are the same only for the feature you are comparing.",
      example: "🔵 and 🔵 have the same color and shape. 🔵 and 🔺 have different shapes.",
      question: "Which one is the same as 🟡?",
      choices: ["🟡", "🔵", "🟩"],
      answer: "🟡",
      why: "Both are yellow circles.",
      activity: "Find two socks that match and name what is the same.",
      words: [["same", "matching in the way we are looking"], ["different", "not matching"]],
    },
    {
      id: "big-and-small",
      title: "Big and small",
      icon: "🐘",
      bigIdea: "Size tells how much space something takes up.",
      explanation: "Big and small are comparison words. A dog is big beside a mouse but small beside an elephant.",
      example: "🐘 is bigger than 🐭. The mouse is smaller than the elephant.",
      question: "Which circle is smallest?",
      choices: ["●", "⬤", "⚫"],
      answer: "●",
      why: "It takes up the least space.",
      activity: "Make your body big like a giant, then small like a seed.",
      words: [["bigger", "taking up more space"], ["smaller", "taking up less space"]],
    },
    {
      id: "first-shapes",
      title: "Circle, square, triangle",
      icon: "🔺",
      bigIdea: "Shapes are named by features we can see and feel.",
      explanation: "A circle is round. A square has four equal sides. A triangle has three sides.",
      example: "A wheel is like a circle. A block face can be a square. A roof can look like a triangle.",
      question: "Which shape has three sides?",
      choices: ["● Circle", "■ Square", "▲ Triangle"],
      answer: "▲ Triangle",
      why: "A triangle has three straight sides and three corners.",
      activity: "Draw a circle in the air, then make a triangle with your fingers.",
      words: [["side", "a straight edge"], ["corner", "where two sides meet"]],
    },
    {
      id: "where-is-it",
      title: "Above, below, beside",
      icon: "📍",
      bigIdea: "Position words tell where something is.",
      explanation: "Above means higher. Below means lower. Beside means next to.",
      example: "A hat is above your eyes. Shoes are below your knees. Your arms are beside your body.",
      question: "The star is ___ the cloud: ⭐\n☁️",
      choices: ["above", "below", "beside"],
      answer: "above",
      why: "The star is higher than the cloud.",
      activity: "Put a toy above a pillow, below it, and beside it.",
      words: [["above", "higher than"], ["below", "lower than"], ["beside", "next to"]],
    },
    {
      id: "simple-patterns",
      title: "Patterns repeat",
      icon: "🟣",
      bigIdea: "A pattern follows a rule that repeats.",
      explanation: "Say the colors aloud: purple, yellow, purple, yellow. Hearing the repeat helps you predict what comes next.",
      example: "🟣 🟡 🟣 🟡 …",
      question: "What comes next? 🔴 🔵 🔴 🔵 ___",
      choices: ["🔴", "🔵", "🟢"],
      answer: "🔴",
      why: "The rule repeats red, blue.",
      activity: "Clap, tap, clap, tap. Keep the pattern going.",
      words: [["pattern", "a rule that repeats"], ["next", "what comes after"]],
    },
    {
      id: "more-and-fewer",
      title: "More and fewer",
      icon: "🫐",
      bigIdea: "More means a greater number. Fewer means a smaller number.",
      explanation: "Line objects up one-to-one. The group with leftovers has more.",
      example: "🫐🫐🫐 has more berries than 🫐🫐.",
      question: "Which group has more fish?",
      choices: ["🐟", "🐟🐟🐟", "🐟🐟"],
      answer: "🐟🐟🐟",
      why: "Three fish is more than one or two fish.",
      activity: "Make one pile of two blocks and one pile of four. Point to the pile with more.",
      words: [["more", "a greater number"], ["fewer", "a smaller number"]],
    },
  ],
  [
    {
      id: "count-to-twenty",
      title: "Counting to 20",
      icon: "🔢",
      bigIdea: "Numbers keep the same order, and each next number means one more.",
      explanation: "After 9, the teen numbers begin with one group of ten and some extra ones. Thirteen is ten and three more.",
      example: "10 blocks + 4 blocks = 14 blocks.",
      question: "What number comes after 16?",
      choices: ["15", "17", "18"],
      answer: "17",
      why: "Counting forward adds one: 16, 17.",
      activity: "Take 20 steps and say one number for every step.",
      words: [["teen number", "a number from 13 through 19"], ["one more", "the next counting number"]],
    },
    {
      id: "number-order",
      title: "Put numbers in order",
      icon: "🚂",
      bigIdea: "A number line places smaller numbers before larger numbers.",
      explanation: "Imagine numbers as train cars. Moving right means the numbers grow. Moving left means they shrink.",
      example: "3, 4, 5 are in order from least to greatest.",
      question: "Which number belongs between 7 and 9?",
      choices: ["6", "8", "10"],
      answer: "8",
      why: "The counting order is 7, 8, 9.",
      activity: "Write 1–10 on scraps of paper, mix them, then rebuild the number line.",
      words: [["least", "smallest amount"], ["greatest", "largest amount"]],
    },
    {
      id: "addition-stories",
      title: "Addition joins",
      icon: "➕",
      bigIdea: "Addition joins amounts to find how many altogether.",
      explanation: "Start with one group, bring in another group, then count everything. The plus sign means join.",
      example: "🍓🍓 + 🍓 = 3 strawberries.",
      question: "Mia has 3 crayons and gets 2 more. How many now?",
      choices: ["4", "5", "6"],
      answer: "5",
      why: "Count on two from 3: four, five.",
      activity: "Join a group of two toys and a group of three toys. Count the total.",
      words: [["add", "join amounts"], ["total", "how many altogether"]],
    },
    {
      id: "subtraction-stories",
      title: "Subtraction takes away",
      icon: "➖",
      bigIdea: "Subtraction can tell how many remain after some leave.",
      explanation: "Begin with the whole group. Move away the amount being taken. Count what is left.",
      example: "5 balloons − 2 balloons = 3 balloons.",
      question: "There are 7 ducks. 3 swim away. How many remain?",
      choices: ["3", "4", "5"],
      answer: "4",
      why: "Take three counts back from 7: six, five, four.",
      activity: "Set out six blocks. Hide two. Count the blocks you can still see.",
      words: [["subtract", "take away or find a difference"], ["remain", "are still left"]],
    },
    {
      id: "flat-shapes",
      title: "2D shape detectives",
      icon: "🟦",
      bigIdea: "Flat shapes can be described by sides and corners.",
      explanation: "Size and turning do not change a shape's name. A tiny tilted square is still a square because its features stay the same.",
      example: "A rectangle has four sides and four square corners. Opposite sides are equal.",
      question: "Which shape has no straight sides and no corners?",
      choices: ["circle", "triangle", "rectangle"],
      answer: "circle",
      why: "A circle has one continuous curved edge.",
      activity: "Go on a shape hunt. Find a circle, rectangle and triangle in the room.",
      words: [["2D", "flat: having length and width"], ["feature", "a detail that helps describe something"]],
    },
    {
      id: "solid-shapes",
      title: "3D shapes you can hold",
      icon: "🧊",
      bigIdea: "Solid shapes have length, width and depth.",
      explanation: "A sphere rolls smoothly. A cube has six square faces. A cylinder has two flat circles and one curved surface.",
      example: "A ball is like a sphere; a can is like a cylinder.",
      question: "Which solid is most like a dice?",
      choices: ["cube", "sphere", "cylinder"],
      answer: "cube",
      why: "A dice has six equal square faces, like a cube.",
      activity: "Sort safe objects by whether they roll, slide, or do both.",
      words: [["3D", "solid: having length, width and depth"], ["face", "a flat surface on a solid"]],
    },
    {
      id: "halves-and-wholes",
      title: "Whole and half",
      icon: "🍊",
      bigIdea: "Two equal halves make one whole.",
      explanation: "A half must be one of two equal parts. If one piece is larger, the pieces are not halves.",
      example: "Cutting a sandwich into two equal pieces makes two halves.",
      question: "How many equal halves make a whole?",
      choices: ["1", "2", "3"],
      answer: "2",
      why: "Half means one of two equal parts.",
      activity: "Fold a paper circle so both sides match. Open it to see two halves.",
      words: [["whole", "all of one thing"], ["half", "one of two equal parts"]],
    },
    {
      id: "measure-with-objects",
      title: "Measure and compare",
      icon: "📏",
      bigIdea: "Measurement tells how long, tall or heavy something is using the same-size unit.",
      explanation: "Place units end to end with no gaps or overlaps. A fair comparison uses the same unit for both objects.",
      example: "A book may be 8 paper clips long.",
      question: "A pencil is 6 blocks long. A crayon is 4 blocks long. Which is longer?",
      choices: ["pencil", "crayon", "same length"],
      answer: "pencil",
      why: "Six same-size blocks is a greater length than four.",
      activity: "Measure a book and a spoon with the same building block.",
      words: [["measure", "find an amount using a unit"], ["unit", "one repeated measuring piece"]],
    },
  ],
  [
    {
      id: "place-value",
      title: "Place value",
      icon: "🏠",
      bigIdea: "A digit's value depends on its place.",
      explanation: "Our number system groups by tens. In 347, the 3 means three hundreds, the 4 means four tens, and the 7 means seven ones.",
      example: "347 = 300 + 40 + 7.",
      question: "What is the value of 6 in 264?",
      choices: ["6", "60", "600"],
      answer: "60",
      why: "The 6 is in the tens place, so it represents six tens.",
      activity: "Build a three-digit number with bundles of ten straws and single straws.",
      words: [["digit", "one symbol from 0 to 9"], ["place value", "the value given by a digit's position"]],
    },
    {
      id: "addition-strategies",
      title: "Add by making friendly numbers",
      icon: "🧠",
      bigIdea: "Numbers can be regrouped without changing the total.",
      explanation: "Break numbers apart to make tens. For 38 + 27, move 2 from 27 to 38. Now solve 40 + 25.",
      example: "38 + 27 = 40 + 25 = 65.",
      question: "What is 46 + 19?",
      choices: ["55", "65", "75"],
      answer: "65",
      why: "Move 4 from 19 to 46: 50 + 15 = 65.",
      activity: "Explain two different ways to solve 29 + 16.",
      words: [["regroup", "rearrange into useful groups"], ["sum", "the result of addition"]],
    },
    {
      id: "multiplication-groups",
      title: "Multiplication makes equal groups",
      icon: "✖️",
      bigIdea: "Multiplication is a quick way to count equal-size groups.",
      explanation: "The expression 4 × 3 can mean four groups with three in every group. It connects to 3 + 3 + 3 + 3.",
      example: "Four bags with 3 marbles each hold 12 marbles.",
      question: "There are 5 rows of 4 chairs. How many chairs?",
      choices: ["9", "20", "25"],
      answer: "20",
      why: "Five equal groups of four make 4 + 4 + 4 + 4 + 4 = 20.",
      activity: "Make three equal rows of five small objects and count the array.",
      words: [["factor", "a number being multiplied"], ["product", "the result of multiplication"]],
    },
    {
      id: "division-sharing",
      title: "Division shares equally",
      icon: "➗",
      bigIdea: "Division separates a total into equal groups.",
      explanation: "Twelve divided by three asks how many go in each of three equal groups—or how many groups of three fit in twelve.",
      example: "12 berries shared by 3 children gives 4 berries each.",
      question: "18 stickers are shared equally among 6 friends. How many each?",
      choices: ["2", "3", "4"],
      answer: "3",
      why: "Six groups of three make 18.",
      activity: "Share 20 counters equally among four cups.",
      words: [["divide", "separate into equal groups"], ["quotient", "the result of division"]],
    },
    {
      id: "fraction-size",
      title: "Understanding fractions",
      icon: "🥧",
      bigIdea: "A fraction names equal parts of one whole or one set.",
      explanation: "The denominator tells how many equal parts make the whole. The numerator tells how many of those parts we mean.",
      example: "3/4 means three of four equal parts.",
      question: "Which is larger when the wholes are equal?",
      choices: ["1/4", "3/4", "They are equal"],
      answer: "3/4",
      why: "Both use fourths, and three fourths includes more pieces than one fourth.",
      activity: "Fold a paper strip into fourths and shade three parts.",
      words: [["numerator", "how many parts are chosen"], ["denominator", "how many equal parts make the whole"]],
    },
    {
      id: "perimeter-and-area",
      title: "Perimeter and area",
      icon: "🖼️",
      bigIdea: "Perimeter measures around; area measures the space inside.",
      explanation: "Imagine fencing a garden for perimeter and covering its soil for area. They answer different questions and use different units.",
      example: "A 5-by-3 rectangle has area 15 square units and perimeter 16 units.",
      question: "A rectangle is 6 m long and 2 m wide. What is its area?",
      choices: ["8 m²", "12 m²", "16 m²"],
      answer: "12 m²",
      why: "Area = length × width = 6 × 2.",
      activity: "Draw two shapes with area 12 squares but different perimeters.",
      words: [["perimeter", "distance around a shape"], ["area", "amount of surface inside a boundary"]],
    },
    {
      id: "data-and-graphs",
      title: "Read data like a detective",
      icon: "📊",
      bigIdea: "Graphs organize data so patterns are easier to see.",
      explanation: "Always read the title, labels and scale before comparing bars or points. A taller bar only means more if the scale says so.",
      example: "If each picture stands for 2 votes, four pictures represent 8 votes.",
      question: "A bar reaches 15 and another reaches 9. What is the difference?",
      choices: ["5", "6", "24"],
      answer: "6",
      why: "The difference is 15 − 9 = 6.",
      activity: "Survey family members' favorite fruit and draw a bar graph.",
      words: [["data", "information collected to answer a question"], ["scale", "the value represented by each step on a graph"]],
    },
    {
      id: "angles-and-turns",
      title: "Angles measure turns",
      icon: "📐",
      bigIdea: "An angle tells how much one direction turns toward another.",
      explanation: "A right angle is a quarter turn. Acute angles are smaller than a right angle; obtuse angles are larger but smaller than a half turn.",
      example: "The corner of a square is a 90° right angle.",
      question: "Which angle is smaller than 90°?",
      choices: ["acute", "right", "obtuse"],
      answer: "acute",
      why: "By definition, an acute angle measures less than 90°.",
      activity: "Use two pencils as rays and make acute, right and obtuse angles.",
      words: [["vertex", "the point where two rays meet"], ["degree", "a unit for measuring angles"]],
    },
  ],
  [
    {
      id: "decimal-place-value",
      title: "Decimals extend place value",
      icon: "🔬",
      bigIdea: "Places to the right of the decimal point represent parts smaller than one.",
      explanation: "Moving one place left multiplies value by 10; moving one place right divides it by 10. In 3.47, the 4 means four tenths and the 7 means seven hundredths.",
      example: "3.47 = 3 + 4/10 + 7/100.",
      question: "Which number is greatest?",
      choices: ["0.8", "0.75", "0.805"],
      answer: "0.805",
      why: "Write equal places: 0.800, 0.750, 0.805. Eight hundred five thousandths is greatest.",
      activity: "Place 0.2, 0.35 and 0.9 on a number line from 0 to 1.",
      words: [["tenth", "one of ten equal parts"], ["hundredth", "one of one hundred equal parts"]],
    },
    {
      id: "fraction-operations",
      title: "Add fractions with meaning",
      icon: "🍕",
      bigIdea: "Fractions can be added directly only when their pieces are the same size.",
      explanation: "A common denominator renames fractions using equal-size pieces. You may add numerators after the units match, just as you add meters to meters.",
      example: "1/3 + 1/6 = 2/6 + 1/6 = 3/6 = 1/2.",
      question: "What is 1/4 + 2/4?",
      choices: ["3/4", "3/8", "2/8"],
      answer: "3/4",
      why: "The fourth-size pieces already match, so add the selected pieces: 1 + 2 = 3 fourths.",
      activity: "Draw fraction bars to show why 1/2 and 2/4 are equivalent.",
      words: [["equivalent", "equal in value"], ["common denominator", "a shared name for equal-size fraction pieces"]],
    },
    {
      id: "ratios",
      title: "Ratios compare quantities",
      icon: "⚖️",
      bigIdea: "A ratio describes how one quantity relates to another.",
      explanation: "Ratios can compare part to part or part to whole. Multiplying or dividing both terms by the same number keeps the relationship equivalent.",
      example: "2 red beads for every 3 blue beads gives a red-to-blue ratio of 2:3.",
      question: "Which ratio is equivalent to 3:4?",
      choices: ["6:8", "6:7", "9:16"],
      answer: "6:8",
      why: "Both terms in 3:4 were multiplied by 2.",
      activity: "Mix a pretend color recipe with two blue marks for every one yellow mark. Scale it up three times.",
      words: [["ratio", "a comparison using division"], ["equivalent ratio", "a different pair with the same relationship"]],
    },
    {
      id: "percent",
      title: "Percent means out of 100",
      icon: "%",
      bigIdea: "Percent is a common scale that compares amounts to 100.",
      explanation: "Because every percent uses the same whole of 100, percentages make comparisons convenient. Twenty-five percent equals 25/100, which simplifies to 1/4.",
      example: "50% = 50/100 = 1/2 = 0.5.",
      question: "What is 20% of 60?",
      choices: ["6", "12", "20"],
      answer: "12",
      why: "10% of 60 is 6, so 20% is twice that: 12.",
      activity: "Shade 35 squares on a 100-square grid and write the fraction, decimal and percent.",
      words: [["percent", "a rate per one hundred"], ["rate", "a comparison of quantities with different units or scales"]],
    },
    {
      id: "negative-numbers",
      title: "Negative numbers show direction",
      icon: "🌡️",
      bigIdea: "Numbers below zero describe amounts or positions in the opposite direction.",
      explanation: "On a number line, values increase to the right. A number farther right is greater, so −2 is greater than −7 even though 7 is the larger digit.",
      example: "A temperature rising from −5°C to 2°C changes by 7 degrees.",
      question: "Which number is greatest?",
      choices: ["−8", "−3", "−10"],
      answer: "−3",
      why: "−3 lies farthest to the right on the number line.",
      activity: "Draw a vertical number line as an elevator with floors below and above ground.",
      words: [["negative", "less than zero"], ["opposite", "the same distance from zero in the other direction"]],
    },
    {
      id: "expressions-and-order",
      title: "Order of operations",
      icon: "🧩",
      bigIdea: "Shared conventions make a numerical expression have one clear meaning.",
      explanation: "Group symbols come first, then exponents, multiplication or division from left to right, and addition or subtraction from left to right.",
      example: "3 + 4 × 2 = 3 + 8 = 11, not 14.",
      question: "What is 18 ÷ 3 + 2 × 4?",
      choices: ["14", "32", "16"],
      answer: "14",
      why: "Division and multiplication first: 6 + 8 = 14.",
      activity: "Add parentheses to 5 + 3 × 2 to make the result 16.",
      words: [["expression", "numbers and operations that represent a value"], ["convention", "an agreed rule that makes meaning clear"]],
    },
    {
      id: "variables-equations",
      title: "Variables and equations",
      icon: "🕵️",
      bigIdea: "A variable represents a number that may be unknown or able to change.",
      explanation: "An equation says two expressions have equal value. Solving means finding values that keep the balance true; whatever you do to one side must be done to the other.",
      example: "x + 7 = 19, so x = 12 because 12 + 7 = 19.",
      question: "Solve 3x = 24.",
      choices: ["6", "8", "21"],
      answer: "8",
      why: "Divide both sides by 3: x = 24 ÷ 3 = 8.",
      activity: "Write an equation for: three identical bags hold 27 marbles altogether.",
      words: [["variable", "a symbol representing a number"], ["solution", "a value that makes an equation true"]],
    },
    {
      id: "probability",
      title: "Probability measures uncertainty",
      icon: "🎲",
      bigIdea: "Probability compares favorable outcomes with all equally likely outcomes.",
      explanation: "Probability ranges from 0, impossible, to 1, certain. A long experiment may not match the prediction exactly, but results often move closer as trials increase.",
      example: "A fair six-sided die has probability 1/6 of landing on 4.",
      question: "A bag has 3 blue and 2 green tokens. What is P(blue)?",
      choices: ["2/5", "3/5", "3/2"],
      answer: "3/5",
      why: "Three of the five equally likely tokens are blue.",
      activity: "Flip a coin 20 times. Compare your experimental result with the theoretical probability of 1/2.",
      words: [["outcome", "one possible result"], ["probability", "a number describing how likely an event is"]],
    },
  ],
];

const scienceLessons: LearningLesson[][] = [
  [
    {
      id: "five-senses",
      title: "Our senses notice",
      icon: "👀",
      bigIdea: "Eyes, ears, nose, tongue and skin help us learn about the world.",
      explanation: "We can look, listen, smell, taste and touch. Scientists begin by noticing carefully. Ask a grown-up before tasting anything.",
      example: "Eyes notice a red apple. A nose notices its smell. Skin feels whether it is smooth.",
      question: "Which body part helps you hear music?",
      choices: ["ears", "nose", "tongue"],
      answer: "ears",
      why: "Ears detect sounds.",
      activity: "Close your eyes and name two safe sounds you hear.",
      words: [["sense", "a way the body notices information"], ["observe", "notice carefully"]],
    },
    {
      id: "living-things",
      title: "Living and nonliving",
      icon: "🌱",
      bigIdea: "Living things grow and need resources. Nonliving things do not grow by themselves.",
      explanation: "Plants and animals are living. A rock is nonliving. A toy can move when we push it, but it does not eat or grow.",
      example: "A puppy grows into a dog. A ball does not grow into a bigger ball.",
      question: "Which one is living?",
      choices: ["🌻 flower", "🪨 rock", "🧸 toy"],
      answer: "🌻 flower",
      why: "A flower is a plant. It grows and needs water and light.",
      activity: "Find one living thing and one nonliving thing. Tell how you know.",
      words: [["living", "alive and able to grow"], ["nonliving", "not alive"]],
    },
    {
      id: "what-living-things-need",
      title: "What living things need",
      icon: "💧",
      bigIdea: "Living things need water, energy and a suitable place to live.",
      explanation: "Animals get energy from food. Plants use sunlight to help make food. Different living things need different amounts.",
      example: "A bird needs water, food, air and shelter. A plant needs water, air, light and room to grow.",
      question: "What does a plant need to grow?",
      choices: ["water and light", "a toy car", "paint"],
      answer: "water and light",
      why: "Water and light help the plant stay alive and grow.",
      activity: "Help care for a plant and notice one change each day.",
      words: [["need", "something important for staying alive"], ["shelter", "a protected place"]],
    },
    {
      id: "weather",
      title: "Weather changes",
      icon: "🌦️",
      bigIdea: "Weather describes the air and sky around us right now.",
      explanation: "A day can be sunny, cloudy, rainy, snowy, windy, warm or cold. Weather can change from morning to afternoon.",
      example: "Dark clouds may bring rain. Moving leaves can show that wind is blowing.",
      question: "What could you wear on a rainy day?",
      choices: ["raincoat", "swimsuit", "ice skates"],
      answer: "raincoat",
      why: "A raincoat helps keep water off your clothes.",
      activity: "Look outside with a grown-up. Describe the clouds, wind and temperature.",
      words: [["weather", "what the air and sky are like now"], ["temperature", "how hot or cold something is"]],
    },
    {
      id: "day-and-night",
      title: "Day and night",
      icon: "🌞",
      bigIdea: "The Sun lights one side of Earth at a time.",
      explanation: "Earth turns slowly. When our part faces the Sun, it is day. When it turns away, it is night.",
      example: "A spinning ball and a flashlight can model day and night.",
      question: "What gives Earth daylight?",
      choices: ["the Sun", "the Moon", "clouds"],
      answer: "the Sun",
      why: "Sunlight brightens the side of Earth facing the Sun.",
      activity: "Shine a flashlight on a ball while a grown-up slowly turns it.",
      words: [["day", "the time our area faces the Sun"], ["night", "the time our area faces away from the Sun"]],
    },
    {
      id: "plants-grow",
      title: "From seed to plant",
      icon: "🌻",
      bigIdea: "A seed can grow into a new plant when conditions are right.",
      explanation: "A seed takes in water. A root grows down and a shoot grows up. Leaves open toward light.",
      example: "Seed → root → shoot → young plant.",
      question: "Which part usually grows down first?",
      choices: ["root", "flower", "fruit"],
      answer: "root",
      why: "The first root anchors the plant and begins taking in water.",
      activity: "Sprout a bean in a damp paper towel with a grown-up.",
      words: [["seed", "a young plant with stored food inside"], ["root", "the part that anchors a plant and takes in water"]],
    },
    {
      id: "push-and-pull",
      title: "Pushes and pulls",
      icon: "🛒",
      bigIdea: "A push or pull can start, stop or change motion.",
      explanation: "Push means move away from you. Pull means move toward you. A stronger push can change motion more.",
      example: "You push a toy car forward and pull a wagon behind you.",
      question: "Opening a drawer toward you is usually a…",
      choices: ["pull", "push", "sound"],
      answer: "pull",
      why: "The drawer moves toward you.",
      activity: "Roll a ball softly, then with a stronger push. Compare how far it travels.",
      words: [["push", "a force away"], ["pull", "a force toward"]],
    },
    {
      id: "sink-or-float",
      title: "Sink or float",
      icon: "🛶",
      bigIdea: "Some objects stay near the water's surface and others move downward.",
      explanation: "What something is made of and how its mass is spread out both matter. A heavy metal ship can float because of its hollow shape.",
      example: "A dry leaf may float. A small stone usually sinks.",
      question: "Which object is most likely to float?",
      choices: ["empty plastic cup", "solid stone", "metal coin"],
      answer: "empty plastic cup",
      why: "Its hollow shape includes air and spreads its mass over more water.",
      activity: "With a grown-up, predict and test three waterproof objects in a bowl of water.",
      words: [["float", "stay supported near a liquid's surface"], ["sink", "move down through a liquid"]],
    },
  ],
  [
    {
      id: "life-cycles",
      title: "Life cycles",
      icon: "🦋",
      bigIdea: "Living things change through stages and make new living things of the same kind.",
      explanation: "A butterfly begins as an egg, becomes a caterpillar, forms a chrysalis and emerges as an adult. The adult can begin the cycle again.",
      example: "Egg → caterpillar → chrysalis → butterfly.",
      question: "Which stage comes after caterpillar?",
      choices: ["chrysalis", "egg", "seed"],
      answer: "chrysalis",
      why: "The caterpillar changes inside a chrysalis before becoming an adult butterfly.",
      activity: "Draw a four-part circle and illustrate the butterfly life cycle.",
      words: [["life cycle", "the stages of a living thing's life"], ["adult", "a fully grown living thing"]],
    },
    {
      id: "plant-parts",
      title: "Plant parts have jobs",
      icon: "🌿",
      bigIdea: "Roots, stems, leaves, flowers and fruits help a plant survive and reproduce.",
      explanation: "Roots absorb water. Stems support and transport. Leaves capture light. Flowers help make seeds, and fruits can protect or spread them.",
      example: "Water can travel from roots through the stem to leaves.",
      question: "Which part captures most sunlight?",
      choices: ["leaves", "roots", "seeds"],
      answer: "leaves",
      why: "Leaves are shaped and positioned to receive light for making food.",
      activity: "Examine a safe plant and sketch each visible part with its job.",
      words: [["transport", "move material from one place to another"], ["reproduce", "make new living things of the same kind"]],
    },
    {
      id: "habitats",
      title: "Habitats are homes",
      icon: "🏞️",
      bigIdea: "A habitat provides the resources and conditions an organism needs.",
      explanation: "Deserts, forests, oceans and ponds are habitats. Each has different water, light, temperature, food and shelter.",
      example: "A camel has features that help it live in a hot, dry desert.",
      question: "Which habitat fits a frog best?",
      choices: ["pond edge", "dry attic", "icy mountaintop"],
      answer: "pond edge",
      why: "A pond edge provides water, food and shelter suited to a frog.",
      activity: "Design a habitat box on paper for an animal you know.",
      words: [["habitat", "the place where an organism lives"], ["resource", "something an organism uses, such as food or shelter"]],
    },
    {
      id: "states-of-matter",
      title: "Solids, liquids and gases",
      icon: "🧊",
      bigIdea: "Matter can behave as a solid, liquid or gas.",
      explanation: "A solid keeps its own shape. A liquid flows and takes its container's shape. A gas spreads to fill available space.",
      example: "Ice, water and water vapor are the same substance in different states.",
      question: "Which state takes the shape of its container but keeps its volume?",
      choices: ["liquid", "solid", "gas"],
      answer: "liquid",
      why: "A liquid flows to match its container while the amount stays the same.",
      activity: "Pour the same water between differently shaped clear cups and observe what changes.",
      words: [["matter", "anything that has mass and takes up space"], ["state", "a form in which matter behaves"]],
    },
    {
      id: "light-and-shadows",
      title: "Light and shadows",
      icon: "🔦",
      bigIdea: "Light travels from a source, and an opaque object can block it to form a shadow.",
      explanation: "Move an object closer to a lamp and its shadow may grow. The shadow shows the outline where light is blocked, not the object's color.",
      example: "Your body blocks sunlight and creates a shadow on the ground.",
      question: "What is needed to make a clear shadow?",
      choices: ["light source and blocking object", "sound and water", "magnet and metal"],
      answer: "light source and blocking object",
      why: "A shadow forms where an object stops light from reaching a surface.",
      activity: "Use a flashlight and toy to explore how distance changes shadow size.",
      words: [["light source", "something that produces light"], ["opaque", "blocking most light"]],
    },
    {
      id: "sound-vibrations",
      title: "Sound begins with vibration",
      icon: "🎸",
      bigIdea: "Vibrating matter pushes nearby matter and creates traveling sound waves.",
      explanation: "A plucked string moves back and forth. It pushes the air, and those changes travel to your ear. Faster vibrations usually make a higher pitch.",
      example: "Touch your throat gently while humming and feel the vibration.",
      question: "What happens first when a guitar makes sound?",
      choices: ["a string vibrates", "light bends", "ice melts"],
      answer: "a string vibrates",
      why: "The vibrating string starts the sound wave in the air.",
      activity: "Stretch a rubber band over a box and compare its sounds when tight and loose.",
      words: [["vibration", "repeated back-and-forth motion"], ["pitch", "how high or low a sound seems"]],
    },
    {
      id: "water-cycle",
      title: "Water travels in a cycle",
      icon: "💧",
      bigIdea: "Water moves among Earth's surface and atmosphere again and again.",
      explanation: "Liquid water evaporates, water vapor cools and condenses into droplets, and precipitation returns water to the surface.",
      example: "A puddle can evaporate, become part of a cloud and later fall as rain.",
      question: "What is water vapor cooling into droplets called?",
      choices: ["condensation", "evaporation", "collection"],
      answer: "condensation",
      why: "Condensation changes gas into liquid droplets.",
      activity: "Watch droplets form outside a cold cup and explain where the water came from.",
      words: [["evaporation", "liquid changing to gas"], ["condensation", "gas changing to liquid"]],
    },
    {
      id: "solar-system",
      title: "Our solar-system neighborhood",
      icon: "🪐",
      bigIdea: "Eight planets and many smaller objects orbit our star, the Sun.",
      explanation: "The Sun's gravity holds the solar system together. Planets are not lined up in space; each travels along its own orbit at a different speed.",
      example: "Earth is the third planet from the Sun and takes about one year to orbit once.",
      question: "What object is at the center of our solar system?",
      choices: ["the Sun", "Earth", "the Moon"],
      answer: "the Sun",
      why: "The planets, including Earth, orbit the Sun.",
      activity: "Make a walking model: one person is the Sun while another slowly orbits as Earth.",
      words: [["orbit", "a curved path around another object due to gravity"], ["planet", "a large round world orbiting a star"]],
    },
  ],
  [
    {
      id: "cells",
      title: "Cells are life's small units",
      icon: "🔬",
      bigIdea: "All living things are made of one or more cells.",
      explanation: "Cells carry out basic life processes. Plant and animal cells share many structures, but plant cells also have a stiff cell wall and chloroplasts.",
      example: "Your skin contains many layers of cells working together as tissue.",
      question: "Which structure helps a plant cell capture light energy?",
      choices: ["chloroplast", "cell wall", "nucleus"],
      answer: "chloroplast",
      why: "Chloroplasts contain molecules that absorb light for photosynthesis.",
      activity: "Draw a model cell as a tiny city and assign jobs to its parts.",
      words: [["cell", "the smallest unit considered alive"], ["organelle", "a specialized structure inside a cell"]],
    },
    {
      id: "ecosystems",
      title: "Ecosystems connect",
      icon: "🕸️",
      bigIdea: "Organisms interact with one another and with nonliving parts of their environment.",
      explanation: "Energy often enters through sunlight, moves through food webs and eventually leaves as heat. Matter such as water and carbon cycles through the system.",
      example: "Grass captures energy, a rabbit eats grass, and a hawk may eat the rabbit.",
      question: "Which organism usually begins a food chain by capturing sunlight?",
      choices: ["producer", "predator", "decomposer"],
      answer: "producer",
      why: "Producers such as plants convert light energy into stored chemical energy.",
      activity: "Draw a food web with at least one producer, two consumers and one decomposer.",
      words: [["ecosystem", "organisms and their physical environment interacting"], ["producer", "an organism that makes its own food"]],
    },
    {
      id: "adaptations",
      title: "Adaptations fit environments",
      icon: "🦎",
      bigIdea: "Inherited traits that improve survival or reproduction can become common over generations.",
      explanation: "An adaptation is not a choice an individual makes. Variation already exists, and environmental conditions influence which traits are passed on more often.",
      example: "Webbed feet help many aquatic birds push against water while swimming.",
      question: "Which is most likely an inherited adaptation for a polar bear?",
      choices: ["thick insulating fur", "learning a route", "a temporary scratch"],
      answer: "thick insulating fur",
      why: "Fur traits can be inherited and improve survival in cold conditions.",
      activity: "Invent an animal for a windy planet and justify three adaptations.",
      words: [["adaptation", "an inherited feature shaped across generations"], ["variation", "differences among individuals"]],
    },
    {
      id: "particles-and-matter",
      title: "Matter is made of particles",
      icon: "⚛️",
      bigIdea: "Tiny particles are always moving, and their arrangement helps explain states of matter.",
      explanation: "Solid particles vibrate in fixed positions. Liquid particles remain close but slide. Gas particles move freely with much more space between them.",
      example: "Heating often increases particle motion, which can cause a change of state.",
      question: "In which state are particles usually farthest apart?",
      choices: ["gas", "liquid", "solid"],
      answer: "gas",
      why: "Gas particles spread through the available space.",
      activity: "Act out particles: stand packed for a solid, slide for a liquid and spread for a gas.",
      words: [["particle", "a tiny piece used in a model of matter"], ["model", "a useful representation of a system or idea"]],
    },
    {
      id: "energy-transformations",
      title: "Energy changes form",
      icon: "⚡",
      bigIdea: "Energy can transfer between objects and transform between forms, while total energy is conserved.",
      explanation: "A battery stores chemical energy. In a flashlight, that energy becomes electrical energy, then light and thermal energy.",
      example: "On a roller coaster, gravitational potential energy changes into kinetic energy downhill.",
      question: "What is the main energy change in a toaster?",
      choices: ["electrical to thermal", "light to chemical", "sound to gravitational"],
      answer: "electrical to thermal",
      why: "Electric current heats the toaster's elements.",
      activity: "Trace at least three energy changes involved in riding a bicycle.",
      words: [["transfer", "movement from one object or place to another"], ["transform", "change from one form to another"]],
    },
    {
      id: "circuits",
      title: "Electric circuits need a loop",
      icon: "💡",
      bigIdea: "Electric charge moves through a complete conducting path.",
      explanation: "A simple circuit needs an energy source, conductors and a device using the energy. An open gap interrupts current; a closed path allows it.",
      example: "A switch controls whether the loop is open or closed.",
      question: "Why does a bulb turn off when a wire is disconnected?",
      choices: ["the circuit is open", "gravity stops", "the bulb loses mass"],
      answer: "the circuit is open",
      why: "The gap prevents current from traveling around a complete loop.",
      activity: "Draw a battery, switch and bulb in one complete circuit loop.",
      words: [["current", "organized movement of electric charge"], ["conductor", "material through which charge moves readily"]],
    },
    {
      id: "forces-and-motion",
      title: "Forces change motion",
      icon: "🚲",
      bigIdea: "An unbalanced force changes an object's speed or direction.",
      explanation: "Balanced forces produce no change in motion. Friction opposes sliding, while gravity pulls masses toward one another.",
      example: "A bicycle speeds up when the forward force is greater than opposing forces.",
      question: "A book rests on a table. What best describes the forces?",
      choices: ["balanced", "only gravity acts", "no forces act"],
      answer: "balanced",
      why: "The table pushes upward while gravity pulls downward with equal effect.",
      activity: "Draw force arrows for a falling ball and for a book resting on a table.",
      words: [["force", "a push or pull"], ["balanced forces", "forces whose combined effect is zero"]],
    },
    {
      id: "earth-systems",
      title: "Earth works as connected systems",
      icon: "🌍",
      bigIdea: "Air, water, rock, ice and life exchange matter and energy.",
      explanation: "A rainstorm connects atmosphere and hydrosphere. Water eroding rock links the hydrosphere and geosphere. Plant roots affect soil and gases.",
      example: "A volcanic eruption can send particles into the atmosphere and change nearby ecosystems.",
      question: "Ocean water evaporating mainly connects which systems?",
      choices: ["hydrosphere and atmosphere", "geosphere and biosphere", "cryosphere and geosphere"],
      answer: "hydrosphere and atmosphere",
      why: "Liquid ocean water enters the air as water vapor.",
      activity: "Choose a local weather event and map at least three Earth-system connections.",
      words: [["system", "interacting parts forming a whole"], ["hydrosphere", "Earth's water"]],
    },
  ],
  [
    {
      id: "atoms-and-elements",
      title: "Atoms and elements",
      icon: "⚛️",
      bigIdea: "Matter is built from atoms; an element is defined by its number of protons.",
      explanation: "Atoms contain protons and neutrons in a nucleus with electrons occupying regions around it. Atoms of carbon always have six protons, though neutron counts can vary.",
      example: "Water is made from hydrogen and oxygen atoms chemically bonded in a 2:1 ratio.",
      question: "What determines an atom's element?",
      choices: ["number of protons", "number of energy levels", "physical size"],
      answer: "number of protons",
      why: "Changing the proton number changes the atom's identity on the periodic table.",
      activity: "Build simple paper models of hydrogen, carbon and oxygen, labeling subatomic particles.",
      words: [["atom", "the smallest unit retaining an element's identity"], ["element", "matter made of atoms with the same proton number"]],
    },
    {
      id: "periodic-patterns",
      title: "The periodic table is a pattern map",
      icon: "🧪",
      bigIdea: "Elements are arranged by atomic number so repeating chemical patterns become visible.",
      explanation: "Rows reflect electron energy levels, while many columns group elements with similar outer-electron behavior. Position helps scientists predict properties.",
      example: "Group 18 noble gases are generally unreactive because their outer electron arrangements are stable.",
      question: "Elements in the same column often share similar…",
      choices: ["chemical behavior", "atomic number", "number of energy levels"],
      answer: "chemical behavior",
      why: "Column patterns are linked to similar outer-electron arrangements.",
      activity: "Choose one periodic-table group and compare three members' properties.",
      words: [["atomic number", "number of protons"], ["periodic", "repeating in a pattern"]],
    },
    {
      id: "chemical-reactions",
      title: "Chemical reactions rearrange atoms",
      icon: "⚗️",
      bigIdea: "Reactions break and form chemical bonds without creating or destroying atoms.",
      explanation: "Reactant atoms are rearranged into products. A balanced equation records conservation of each element, while energy may enter or leave the system.",
      example: "Rust forms when iron reacts with oxygen; the product has different properties from iron metal.",
      question: "Why must chemical equations be balanced?",
      choices: ["atoms are conserved", "molecules never move", "all reactions are reversible"],
      answer: "atoms are conserved",
      why: "The same number of each kind of atom must appear before and after a reaction.",
      activity: "Use colored counters to model and balance H₂ + O₂ → H₂O.",
      words: [["reactant", "starting substance in a reaction"], ["product", "substance formed by a reaction"]],
    },
    {
      id: "energy-transfer",
      title: "Energy transfer and efficiency",
      icon: "🔥",
      bigIdea: "Energy is conserved, but useful energy often spreads into less useful thermal energy.",
      explanation: "Conduction transfers energy through collisions, convection through moving fluids, and radiation through electromagnetic waves. Real devices cannot convert all input into the intended output.",
      example: "A laptop transforms electrical energy into computation, light, sound and heat.",
      question: "Sunlight warming Earth transfers energy mainly by…",
      choices: ["radiation", "conduction", "convection through space"],
      answer: "radiation",
      why: "Electromagnetic waves can cross the vacuum between the Sun and Earth.",
      activity: "Create an energy-flow diagram for a household device, including waste heat.",
      words: [["efficiency", "useful output divided by total input"], ["radiation", "energy transfer by electromagnetic waves"]],
    },
    {
      id: "waves",
      title: "Waves carry energy and information",
      icon: "🌊",
      bigIdea: "Wave behavior connects frequency, wavelength, speed and amplitude.",
      explanation: "Frequency counts cycles per second; wavelength measures one cycle's length. In a fixed medium, higher frequency corresponds to shorter wavelength. Amplitude relates to transferred energy.",
      example: "For sound, higher frequency is heard as higher pitch; larger amplitude is usually heard as greater loudness.",
      question: "If wave speed stays constant and frequency increases, wavelength…",
      choices: ["decreases", "increases", "stays equal"],
      answer: "decreases",
      why: "Wave speed equals frequency × wavelength, so the two change inversely at fixed speed.",
      activity: "Draw two waves with equal wavelength but different amplitudes, then explain the difference.",
      words: [["frequency", "cycles per second"], ["wavelength", "distance between matching points on neighboring cycles"]],
    },
    {
      id: "newtons-laws",
      title: "Newton's laws model motion",
      icon: "🚀",
      bigIdea: "Motion changes when a net force acts, according to mass and acceleration.",
      explanation: "Inertia resists changes in motion. The relationship F = ma links net force, mass and acceleration. Forces arise in interaction pairs acting on different objects.",
      example: "The same push accelerates an empty cart more than a loaded cart because the empty cart has less mass.",
      question: "If net force doubles while mass stays constant, acceleration…",
      choices: ["doubles", "halves", "stays constant"],
      answer: "doubles",
      why: "From a = F/m, acceleration is proportional to net force when mass is fixed.",
      activity: "Design a fair test of how cart mass affects acceleration under a similar push.",
      words: [["inertia", "resistance to a change in motion"], ["net force", "the vector sum of forces"]],
    },
    {
      id: "dna-and-inheritance",
      title: "DNA carries inherited instructions",
      icon: "🧬",
      bigIdea: "DNA sequences contain information used to build molecules and regulate cells.",
      explanation: "Genes are DNA regions whose effects interact with other genes and environments. Inherited variation comes from mutation and reshuffling during reproduction.",
      example: "Siblings share much DNA yet differ because they inherit different combinations and have different experiences.",
      question: "Which statement best describes a gene?",
      choices: ["a region of DNA with biological information", "an entire cell", "a learned behavior"],
      answer: "a region of DNA with biological information",
      why: "Genes are defined regions within DNA, not whole cells or experiences.",
      activity: "Use colored strips to model how two parents can produce different gene combinations.",
      words: [["gene", "a DNA region with a biological function"], ["mutation", "a change in DNA sequence"]],
    },
    {
      id: "deep-time-universe",
      title: "Stars build a changing universe",
      icon: "🌌",
      bigIdea: "Gravity shapes cosmic structure, and stars transform matter over enormous time scales.",
      explanation: "Stars form when gravity contracts gas clouds. Fusion powers stars and creates new nuclei; massive stars can distribute heavier elements. Looking far away also means looking into the past because light takes time to travel.",
      example: "Sunlight reaching Earth is about eight minutes old; light from Andromeda began traveling about 2.5 million years ago.",
      question: "Why do distant galaxies show us the past?",
      choices: ["light takes time to travel", "telescopes store old pictures", "galaxies stop changing"],
      answer: "light takes time to travel",
      why: "We receive the light only after it has crossed the distance between the galaxy and Earth.",
      activity: "Create a scale timeline from the Big Bang to today and mark the late arrival of humans.",
      words: [["fusion", "combining light nuclei and releasing energy"], ["light-year", "the distance light travels in one year"]],
    },
  ],
];

export const LEARNING_COUNTS = {
  mathPerAge: mathLessons.map((lessons) => lessons.length),
  sciencePerAge: scienceLessons.map((lessons) => lessons.length),
  total: mathLessons.flat().length + scienceLessons.flat().length,
};

export function getLearningLessons(subject: Subject, age: number) {
  const safeAge = Math.max(0, Math.min(3, age));
  return subject === "math" ? mathLessons[safeAge] : scienceLessons[safeAge];
}

export function getLearningLesson(subject: Subject, age: number, page: number) {
  const lessons = getLearningLessons(subject, age);
  const index = Math.max(0, Math.min(lessons.length - 1, page - 1));
  return lessons[index];
}
